In [40]:
import numpy as np
import pandas as pd
import ast

In [41]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv("tmdb_5000_credits.csv")

In [42]:
movies=movies.merge(credits,on='title')

In [43]:
# genres 
# id
# keywords
# title
# overview
# cast
# crew

In [44]:
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [45]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [46]:
movies.dropna(inplace=True)

In [47]:
movies.duplicated().sum()

np.int64(0)

In [48]:
def convert(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [49]:
movies['genres']=movies['genres'].apply(convert)

In [50]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [51]:
movies['keywords']=movies['keywords'].apply(convert)

In [52]:
def convert3(obj):
    l=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter !=3:
           l.append(i['name'])
           counter+=1
        else :
            break
    return l

In [53]:
movies['cast']=movies['cast'].apply(convert3)

In [54]:
def fetch_director(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            l.append(i['name'])
            break
    return l

In [55]:
movies['crew']=movies['crew'].apply(fetch_director)

In [56]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [57]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [58]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [59]:
movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [60]:
new_df=movies[['movie_id','title','tags']]

In [61]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [62]:
new_df.head(1)

   movie_id   title                                               tags
0     19995  Avatar  In the 22nd century, a paraplegic Marine is di...

In [63]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [64]:
from sklearn.feature_extraction.text import CountVectorizer

In [65]:
cv=CountVectorizer(max_features=5000,stop_words='english')

In [66]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [67]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [70]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      shape=(5000,), dtype=object)